name = "Wayland_jll"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.21.0+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
EpollShim_jll = "2702e6a9-849d-5ed8-8c21-79e8b8f9ee43"
XML2_jll = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Expat_jll = "2e619515-83b5-522b-bb60-26c02a35a201"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Libffi_jll = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
Expat_jll = "2.2.10"
Libffi_jll = "~3.2.2"
